### ISSUE TITLE
API differs between Node and browser environments

### ISSUE THREAD

**Issue by chrisbartley** [kmalakoff/superagent-ls#1]
I'm seeing differences in the API when comparing usage in Node vs the browser (see example code below).  In short, when I run in Node (v0.12.7), I get an HTTP 401 with a null err and a non-null res, as expected.  But, when I try the HTML version in the browser, I'm getting _non-null_ err and a non-null res.  I expected behavior to be the same in both environments (i.e. null err).

Code I used to test:

``` javascript
var superagent = require('superagent-ls');

superagent
      .post("http://httpbin.org/status/401")
      .send({
               email : "foo@foo.com",
               password : "foobar"
            })
      .end(function(err, res) {
         console.log("HTTP Status Code: " + (res ? res.status : null));
         console.log("err is " + (err == null ? "" : "not ") + "null");
         console.log("res is " + (res == null ? "" : "not ") + "null");
      });
```

``` html
<!DOCTYPE HTML>
<html>
<head>
   <title>Test</title>
   <script src="http://localhost:3000/lib/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
   <script src="http://localhost:3000/lib/superagent/superagent-ls.js" type="text/javascript"></script>
   <script type="application/javascript">
      $(document).ready(function() {
         superagent
               .post("http://httpbin.org/status/401")
               .send({
                        email : "foo@foo.com",
                        password : "foobar"
                     })
               .end(function(err, res) {
                  console.log("HTTP Status Code: " + (res ? res.status : null));
                  console.log("err is " + (err == null ? "" : "not ") + "null");
                  console.log("res is " + (res == null ? "" : "not ") + "null");
               });
      });
   </script>
</head>
<body>
</body>
</html>
```

**Comment by kmalakoff** [comment]
Duplicate: https://github.com/kmalakoff/superagent-ls/issues/2

**Comment by chrisbartley** [comment]
Sorry, why is this a dupe of #2?

**Comment by kmalakoff** [comment]
Sorry, my mistake. Reopening.

**Comment by kmalakoff** [comment]
OK. I've taken a look...

I'm not sure how you ran your test case, but it took me almost 2 hours to figure out superagent's build process (it is browserify- and make-based and does not have a make entry for the browser) so I ended up needing to use webpack to build a version that could be loaded into a browser.

I updated the test to just print out the err and res, and here was my output (I tested both 1.3 and 1.4)....

Using serve:

![using-serve](https://cloud.githubusercontent.com/assets/756520/11374645/e9bed284-928b-11e5-8fb6-c81725732eca.png)

Using the index.html file directly:

![using-index html](https://cloud.githubusercontent.com/assets/756520/11374652/f0207fce-928b-11e5-8744-8310b6aa5c03.png)

It looks like in the first case is only giving a response and the second case is only giving an error so it looks like it is behaving correctly.

Could the problem have to do with how you are bundling up your version for the browser? Maybe you are pulling in the node version instead?

**Comment by chrisbartley** [comment]
Thanks for looking in to this. Glad I wasn't the only one who had a hard time figuring it out.  But, apologies for not sharing the knowledge and making it explicit in my original post.

To generate the `superagent.js` (which I renamed to `superagent-ls.js` for my tests, just to be sure I was using the right thing), I just did an `npm install` and then `make`.  Doing so will create the `superagent.js` file in the current directory.

**Comment by kmalakoff** [comment]
Yes, I did that the first time too, but the make file doesn't use the client module so I needed to use webpack (I couldn't figure out how to make a UMD library with browserify):

Here's the Makefile:

```
superagent.js: lib/node/*.js lib/node/parsers/*.js
    @./node_modules/.bin/browserify \
        --standalone superagent \
        --outfile superagent.js .
```

Here's the browser entry in package.json:

```
  "browser": {
    "./lib/node/index.js": "./lib/client.js",
    "emitter": "component-emitter",
    "reduce": "reduce-component",
    "./test/support/server.js": "./test/support/blank.js"
  },
```

Perhaps, you are trying to use the node module in the browser?

**Comment by chrisbartley** [comment]
Ah, crap.  I'm an idiot and I owe you a beer/beverage.

Here's the deal: to create the superagent-ls.js I was using when I noticed this issue, I mistakenly selected the v1.3.0 tag and downloaded the zip.  I was in your repo, but didn't think or realize that selecting that tag would (obviously, now) get me visionmedia's superagent and not yours.  Duh.  So, when I did a make to build superagent.js, I was getting theirs, not yours.  [sigh]

Many apologies for this mistake.  Cloning your repo from the head, building, and retesting and I do indeed get the correct behavior. That's awesome, and thank you, but I feel terrible for wasting your time.

Serious about the beverage--do you have a tip jar somewhere?

**Comment by kmalakoff** [comment]
Hey, no biggie. We are all in this together trying to get stuff done!

I took this as an opportunity to merge in superagent 1.4 anyways so time well spent.
